name: rosetta-klaytn Release workflow
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Create release/tag branch
        run: |
          export Tag=${{ steps.vars.outputs.tag }}
          echo "Create production release tag: ${Tag%-*}"
          git checkout master
          git tag ${Tag%-*}
          git push origin ${Tag%-*}
