on:
  push: # can use "create" event
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]'
jobs:
  initial-release-rc:
    if: github.ref_name == 'v[0-9]+.[0-9]+.[0-9]+-rc.1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Create release/tag branch
        run: |
          export Tag=${{ steps.vars.outputs.tag }}
          echo "Create to release branch: release/${Tag%-*}"
          git checkout -b release/${Tag%-*}
          git push origin release/${Tag%-*}
      - name: create pull request
        id: create_pr
        run: |
          export Tag=${{ steps.vars.outputs.tag }}
          gh pr create --base ${{ env.base }} --title ${{ env.title }} --head release/${Tag%-*} --body ${{ env.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          base: master
          title: "[rosetta-klaytn]_release/${Tag%-*}"
          body: |
              "This PR is automatically created by CI to release a new official version of ${GITHUB_REPOSITORY}.
               When this PR is approved by someone, a new rosetta-klaytn version will be released."
  update-release-rc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Push commits to release/tag branch
        run: |
          export Tag=${{ steps.vars.outputs.tag }}
          echo "Push to release branch: release/${Tag%-*}"
          git push origin release/${Tag%-*}